/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AirRouteImport } from './routes/air'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as DiscordRouteImport } from './routes/discord'
import { Route as FoundationRouteImport } from './routes/foundation'
import { Route as InstallRouteRouteImport } from './routes/install/route'
import { Route as ManualRouteRouteImport } from './routes/manual/route'
import { Route as MeetupsRouteImport } from './routes/meetups'
import { Route as NewsRouteRouteImport } from './routes/news/route'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PatronsRouteImport } from './routes/patrons'
import { Route as PotatoRouteImport } from './routes/potato'
import { Route as SecurityRouteRouteImport } from './routes/security/route'
import { Route as ServerRouteImport } from './routes/server'
import { Route as SponsorshipsRouteImport } from './routes/sponsorships'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as WorkstationsRouteImport } from './routes/workstations'
import { Route as InstallIndexRouteImport } from './routes/install/index'
import { Route as InstallPcRouteImport } from './routes/install/pc'
import { Route as ManualIndexRouteImport } from './routes/manual/index'
import { Route as ManualSlugRouteImport } from './routes/manual/$slug'
import { Route as ManualTocRouteImport } from './routes/manual/toc'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as SecurityIndexRouteImport } from './routes/security/index'
import { Route as SecurityCreditsRouteImport } from './routes/security/credits'
import { Route as InstallMacArmRouteImport } from './routes/install/mac.arm'
import { Route as InstallMacIntelRouteImport } from './routes/install/mac.intel'
import { Route as NewsYearMonthSlugRouteImport } from './routes/news/$year.$month.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AirRoute = AirRouteImport.update({
  id: '/air',
  path: '/air',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordRoute = DiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationRoute = FoundationRouteImport.update({
  id: '/foundation',
  path: '/foundation',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRouteRoute = InstallRouteRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRouteRoute = ManualRouteRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetupsRoute = MeetupsRouteImport.update({
  id: '/meetups',
  path: '/meetups',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRouteRoute = NewsRouteRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PatronsRoute = PatronsRouteImport.update({
  id: '/patrons',
  path: '/patrons',
  getParentRoute: () => rootRouteImport,
} as any)
const PotatoRoute = PotatoRouteImport.update({
  id: '/potato',
  path: '/potato',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRouteRoute = SecurityRouteRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerRoute = ServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorshipsRoute = SponsorshipsRouteImport.update({
  id: '/sponsorships',
  path: '/sponsorships',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkstationsRoute = WorkstationsRouteImport.update({
  id: '/workstations',
  path: '/workstations',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallIndexRoute = InstallIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstallRouteRoute,
} as any)
const InstallPcRoute = InstallPcRouteImport.update({
  id: '/pc',
  path: '/pc',
  getParentRoute: () => InstallRouteRoute,
} as any)
const ManualIndexRoute = ManualIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManualRouteRoute,
} as any)
const ManualSlugRoute = ManualSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ManualRouteRoute,
} as any)
const ManualTocRoute = ManualTocRouteImport.update({
  id: '/toc',
  path: '/toc',
  getParentRoute: () => ManualRouteRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRouteRoute,
} as any)
const SecurityIndexRoute = SecurityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecurityRouteRoute,
} as any)
const SecurityCreditsRoute = SecurityCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => SecurityRouteRoute,
} as any)
const InstallMacArmRoute = InstallMacArmRouteImport.update({
  id: '/mac/arm',
  path: '/mac/arm',
  getParentRoute: () => InstallRouteRoute,
} as any)
const InstallMacIntelRoute = InstallMacIntelRouteImport.update({
  id: '/mac/intel',
  path: '/mac/intel',
  getParentRoute: () => InstallRouteRoute,
} as any)
const NewsYearMonthSlugRoute = NewsYearMonthSlugRouteImport.update({
  id: '/$year/$month/$slug',
  path: '/$year/$month/$slug',
  getParentRoute: () => NewsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/install': typeof InstallRouteRouteWithChildren
  '/manual': typeof ManualRouteRouteWithChildren
  '/news': typeof NewsRouteRouteWithChildren
  '/security': typeof SecurityRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/air': typeof AirRoute
  '/brand': typeof BrandRoute
  '/discord': typeof DiscordRoute
  '/foundation': typeof FoundationRoute
  '/meetups': typeof MeetupsRoute
  '/partners': typeof PartnersRoute
  '/patrons': typeof PatronsRoute
  '/potato': typeof PotatoRoute
  '/server': typeof ServerRoute
  '/sponsorships': typeof SponsorshipsRoute
  '/teams': typeof TeamsRoute
  '/themes': typeof ThemesRoute
  '/workstations': typeof WorkstationsRoute
  '/install/pc': typeof InstallPcRoute
  '/manual/$slug': typeof ManualSlugRoute
  '/manual/toc': typeof ManualTocRoute
  '/security/credits': typeof SecurityCreditsRoute
  '/install/': typeof InstallIndexRoute
  '/manual/': typeof ManualIndexRoute
  '/news/': typeof NewsIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/install/mac/arm': typeof InstallMacArmRoute
  '/install/mac/intel': typeof InstallMacIntelRoute
  '/news/$year/$month/$slug': typeof NewsYearMonthSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/air': typeof AirRoute
  '/brand': typeof BrandRoute
  '/discord': typeof DiscordRoute
  '/foundation': typeof FoundationRoute
  '/meetups': typeof MeetupsRoute
  '/partners': typeof PartnersRoute
  '/patrons': typeof PatronsRoute
  '/potato': typeof PotatoRoute
  '/server': typeof ServerRoute
  '/sponsorships': typeof SponsorshipsRoute
  '/teams': typeof TeamsRoute
  '/themes': typeof ThemesRoute
  '/workstations': typeof WorkstationsRoute
  '/install/pc': typeof InstallPcRoute
  '/manual/$slug': typeof ManualSlugRoute
  '/manual/toc': typeof ManualTocRoute
  '/security/credits': typeof SecurityCreditsRoute
  '/install': typeof InstallIndexRoute
  '/manual': typeof ManualIndexRoute
  '/news': typeof NewsIndexRoute
  '/security': typeof SecurityIndexRoute
  '/install/mac/arm': typeof InstallMacArmRoute
  '/install/mac/intel': typeof InstallMacIntelRoute
  '/news/$year/$month/$slug': typeof NewsYearMonthSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/install': typeof InstallRouteRouteWithChildren
  '/manual': typeof ManualRouteRouteWithChildren
  '/news': typeof NewsRouteRouteWithChildren
  '/security': typeof SecurityRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/air': typeof AirRoute
  '/brand': typeof BrandRoute
  '/discord': typeof DiscordRoute
  '/foundation': typeof FoundationRoute
  '/meetups': typeof MeetupsRoute
  '/partners': typeof PartnersRoute
  '/patrons': typeof PatronsRoute
  '/potato': typeof PotatoRoute
  '/server': typeof ServerRoute
  '/sponsorships': typeof SponsorshipsRoute
  '/teams': typeof TeamsRoute
  '/themes': typeof ThemesRoute
  '/workstations': typeof WorkstationsRoute
  '/install/pc': typeof InstallPcRoute
  '/manual/$slug': typeof ManualSlugRoute
  '/manual/toc': typeof ManualTocRoute
  '/security/credits': typeof SecurityCreditsRoute
  '/install/': typeof InstallIndexRoute
  '/manual/': typeof ManualIndexRoute
  '/news/': typeof NewsIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/install/mac/arm': typeof InstallMacArmRoute
  '/install/mac/intel': typeof InstallMacIntelRoute
  '/news/$year/$month/$slug': typeof NewsYearMonthSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/install'
    | '/manual'
    | '/news'
    | '/security'
    | '/about'
    | '/air'
    | '/brand'
    | '/discord'
    | '/foundation'
    | '/meetups'
    | '/partners'
    | '/patrons'
    | '/potato'
    | '/server'
    | '/sponsorships'
    | '/teams'
    | '/themes'
    | '/workstations'
    | '/install/pc'
    | '/manual/$slug'
    | '/manual/toc'
    | '/security/credits'
    | '/install/'
    | '/manual/'
    | '/news/'
    | '/security/'
    | '/install/mac/arm'
    | '/install/mac/intel'
    | '/news/$year/$month/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/air'
    | '/brand'
    | '/discord'
    | '/foundation'
    | '/meetups'
    | '/partners'
    | '/patrons'
    | '/potato'
    | '/server'
    | '/sponsorships'
    | '/teams'
    | '/themes'
    | '/workstations'
    | '/install/pc'
    | '/manual/$slug'
    | '/manual/toc'
    | '/security/credits'
    | '/install'
    | '/manual'
    | '/news'
    | '/security'
    | '/install/mac/arm'
    | '/install/mac/intel'
    | '/news/$year/$month/$slug'
  id:
    | '__root__'
    | '/'
    | '/install'
    | '/manual'
    | '/news'
    | '/security'
    | '/about'
    | '/air'
    | '/brand'
    | '/discord'
    | '/foundation'
    | '/meetups'
    | '/partners'
    | '/patrons'
    | '/potato'
    | '/server'
    | '/sponsorships'
    | '/teams'
    | '/themes'
    | '/workstations'
    | '/install/pc'
    | '/manual/$slug'
    | '/manual/toc'
    | '/security/credits'
    | '/install/'
    | '/manual/'
    | '/news/'
    | '/security/'
    | '/install/mac/arm'
    | '/install/mac/intel'
    | '/news/$year/$month/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstallRouteRoute: typeof InstallRouteRouteWithChildren
  ManualRouteRoute: typeof ManualRouteRouteWithChildren
  NewsRouteRoute: typeof NewsRouteRouteWithChildren
  SecurityRouteRoute: typeof SecurityRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AirRoute: typeof AirRoute
  BrandRoute: typeof BrandRoute
  DiscordRoute: typeof DiscordRoute
  FoundationRoute: typeof FoundationRoute
  MeetupsRoute: typeof MeetupsRoute
  PartnersRoute: typeof PartnersRoute
  PatronsRoute: typeof PatronsRoute
  PotatoRoute: typeof PotatoRoute
  ServerRoute: typeof ServerRoute
  SponsorshipsRoute: typeof SponsorshipsRoute
  TeamsRoute: typeof TeamsRoute
  ThemesRoute: typeof ThemesRoute
  WorkstationsRoute: typeof WorkstationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/air': {
      id: '/air'
      path: '/air'
      fullPath: '/air'
      preLoaderRoute: typeof AirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord': {
      id: '/discord'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof DiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundation': {
      id: '/foundation'
      path: '/foundation'
      fullPath: '/foundation'
      preLoaderRoute: typeof FoundationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetups': {
      id: '/meetups'
      path: '/meetups'
      fullPath: '/meetups'
      preLoaderRoute: typeof MeetupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrons': {
      id: '/patrons'
      path: '/patrons'
      fullPath: '/patrons'
      preLoaderRoute: typeof PatronsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/potato': {
      id: '/potato'
      path: '/potato'
      fullPath: '/potato'
      preLoaderRoute: typeof PotatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server': {
      id: '/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof ServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsorships': {
      id: '/sponsorships'
      path: '/sponsorships'
      fullPath: '/sponsorships'
      preLoaderRoute: typeof SponsorshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workstations': {
      id: '/workstations'
      path: '/workstations'
      fullPath: '/workstations'
      preLoaderRoute: typeof WorkstationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install/': {
      id: '/install/'
      path: '/'
      fullPath: '/install/'
      preLoaderRoute: typeof InstallIndexRouteImport
      parentRoute: typeof InstallRouteRoute
    }
    '/install/pc': {
      id: '/install/pc'
      path: '/pc'
      fullPath: '/install/pc'
      preLoaderRoute: typeof InstallPcRouteImport
      parentRoute: typeof InstallRouteRoute
    }
    '/manual/': {
      id: '/manual/'
      path: '/'
      fullPath: '/manual/'
      preLoaderRoute: typeof ManualIndexRouteImport
      parentRoute: typeof ManualRouteRoute
    }
    '/manual/$slug': {
      id: '/manual/$slug'
      path: '/$slug'
      fullPath: '/manual/$slug'
      preLoaderRoute: typeof ManualSlugRouteImport
      parentRoute: typeof ManualRouteRoute
    }
    '/manual/toc': {
      id: '/manual/toc'
      path: '/toc'
      fullPath: '/manual/toc'
      preLoaderRoute: typeof ManualTocRouteImport
      parentRoute: typeof ManualRouteRoute
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRouteRoute
    }
    '/security/': {
      id: '/security/'
      path: '/'
      fullPath: '/security/'
      preLoaderRoute: typeof SecurityIndexRouteImport
      parentRoute: typeof SecurityRouteRoute
    }
    '/security/credits': {
      id: '/security/credits'
      path: '/credits'
      fullPath: '/security/credits'
      preLoaderRoute: typeof SecurityCreditsRouteImport
      parentRoute: typeof SecurityRouteRoute
    }
    '/install/mac/arm': {
      id: '/install/mac/arm'
      path: '/mac/arm'
      fullPath: '/install/mac/arm'
      preLoaderRoute: typeof InstallMacArmRouteImport
      parentRoute: typeof InstallRouteRoute
    }
    '/install/mac/intel': {
      id: '/install/mac/intel'
      path: '/mac/intel'
      fullPath: '/install/mac/intel'
      preLoaderRoute: typeof InstallMacIntelRouteImport
      parentRoute: typeof InstallRouteRoute
    }
    '/news/$year/$month/$slug': {
      id: '/news/$year/$month/$slug'
      path: '/$year/$month/$slug'
      fullPath: '/news/$year/$month/$slug'
      preLoaderRoute: typeof NewsYearMonthSlugRouteImport
      parentRoute: typeof NewsRouteRoute
    }
  }
}

interface InstallRouteRouteChildren {
  InstallPcRoute: typeof InstallPcRoute
  InstallIndexRoute: typeof InstallIndexRoute
  InstallMacArmRoute: typeof InstallMacArmRoute
  InstallMacIntelRoute: typeof InstallMacIntelRoute
}

const InstallRouteRouteChildren: InstallRouteRouteChildren = {
  InstallPcRoute: InstallPcRoute,
  InstallIndexRoute: InstallIndexRoute,
  InstallMacArmRoute: InstallMacArmRoute,
  InstallMacIntelRoute: InstallMacIntelRoute,
}

const InstallRouteRouteWithChildren = InstallRouteRoute._addFileChildren(
  InstallRouteRouteChildren,
)

interface ManualRouteRouteChildren {
  ManualSlugRoute: typeof ManualSlugRoute
  ManualTocRoute: typeof ManualTocRoute
  ManualIndexRoute: typeof ManualIndexRoute
}

const ManualRouteRouteChildren: ManualRouteRouteChildren = {
  ManualSlugRoute: ManualSlugRoute,
  ManualTocRoute: ManualTocRoute,
  ManualIndexRoute: ManualIndexRoute,
}

const ManualRouteRouteWithChildren = ManualRouteRoute._addFileChildren(
  ManualRouteRouteChildren,
)

interface NewsRouteRouteChildren {
  NewsIndexRoute: typeof NewsIndexRoute
  NewsYearMonthSlugRoute: typeof NewsYearMonthSlugRoute
}

const NewsRouteRouteChildren: NewsRouteRouteChildren = {
  NewsIndexRoute: NewsIndexRoute,
  NewsYearMonthSlugRoute: NewsYearMonthSlugRoute,
}

const NewsRouteRouteWithChildren = NewsRouteRoute._addFileChildren(
  NewsRouteRouteChildren,
)

interface SecurityRouteRouteChildren {
  SecurityCreditsRoute: typeof SecurityCreditsRoute
  SecurityIndexRoute: typeof SecurityIndexRoute
}

const SecurityRouteRouteChildren: SecurityRouteRouteChildren = {
  SecurityCreditsRoute: SecurityCreditsRoute,
  SecurityIndexRoute: SecurityIndexRoute,
}

const SecurityRouteRouteWithChildren = SecurityRouteRoute._addFileChildren(
  SecurityRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstallRouteRoute: InstallRouteRouteWithChildren,
  ManualRouteRoute: ManualRouteRouteWithChildren,
  NewsRouteRoute: NewsRouteRouteWithChildren,
  SecurityRouteRoute: SecurityRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AirRoute: AirRoute,
  BrandRoute: BrandRoute,
  DiscordRoute: DiscordRoute,
  FoundationRoute: FoundationRoute,
  MeetupsRoute: MeetupsRoute,
  PartnersRoute: PartnersRoute,
  PatronsRoute: PatronsRoute,
  PotatoRoute: PotatoRoute,
  ServerRoute: ServerRoute,
  SponsorshipsRoute: SponsorshipsRoute,
  TeamsRoute: TeamsRoute,
  ThemesRoute: ThemesRoute,
  WorkstationsRoute: WorkstationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
